### ISSUE TITLE
Bug: Memory leak in GitHub PR Conversation view

### ISSUE THREAD

**Issue by kaicataldo** [prettier/prettier-chrome-extension#70]
There's currently a memory leak in the GitHub PR `Conversation` view when editing an existing comment.

#### Steps to reproduce
1. Navigate to an existing PR that you have commented on
2. Edit the comment
3. Click the Prettier button repeatedly

I think this is caused by [these lines of code](https://github.com/prettier/prettier-chrome-extension/blob/master/extension/src/content/index.js#L149-L161), because it is binding the click event listener repeatedly. We can't remove this, though, because it then doesn't bind the button in the `Files changed` view.

**Comment by nickmccurdy** [comment]
If the issue is the same event listener being registered multiple times for the same element, we should be able to fix it by declaring the event listener outside this function scope (if we can access `textArea` from the button's click event). `addEventListener` will not do anything if it has already been called with the same event listener function reference, but it doesn't work with our current code because we create a new function reference on every call (similar issue to creating inline handlers on React components using `React.pure` or `PureComponent` that have expensive render processes).
